lib/chankins/web/router.ex
defmodule Chankins.Web.Router do
  use Chankins.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Chankins.Web do
    pipe_through :browser # Use the default browser stack

    get "/", ProjectController, :index
    get "/changenotes", ChangeNotesController, :show
    resources "/projects", ProjectController
    resources "/releases", ReleaseController
    resources "/versions", VersionController
    resources "/features", FeatureController
    resources "/parameters", ParameterController

  end

  # Other scopes may use custom stacks.
   scope "/api", Chankins.Web, as: :api do
     pipe_through :api
     resources "/projects", API.ProjectController
    resources "/releases", API.ReleaseController
    resources "/versions", API.VersionController
    resources "/features", API.FeatureController
    resources "/parameters", API.ParameterController
   end
end

lib/chankins/web/controllers/api/version_controller.ex
defmodule Chankins.Web.API.VersionController do
  use Chankins.Web, :controller

  alias Chankins.ChangeManagement
  alias Chankins.ChangeManagement.Version

  action_fallback Chankins.Web.FallbackController

  def index(conn, _params) do
    versions = ChangeManagement.list_versions()
    render(conn, "index.json", versions: versions)
  end

  def create(conn, %{"version" => version_params}) do
    with {:ok, %Version{} = version} <- ChangeManagement.create_version(version_params) do
    version = ChangeManagement.get_version!(version.id)
      conn
      |> put_status(:created)
      |> put_resp_header("location", api_version_path(conn, :show, version))
      |> render("show.json", version: version)
    end
  end

  def show(conn, %{"id" => id}) do
    version = ChangeManagement.get_version!(id)
    render(conn, "show.json", version: version)
  end

  def update(conn, %{"id" => id, "version" => version_params}) do
    version = ChangeManagement.get_version!(id)

    with {:ok, %Version{} = version} <- ChangeManagement.update_version(version, version_params) do
      render(conn, "show.json", version: version)
    end
  end

  def delete(conn, %{"id" => id}) do
    version = ChangeManagement.get_version!(id)
    with {:ok, %Version{}} <- ChangeManagement.delete_version(version) do
      send_resp(conn, :no_content, "")
    end
  end
end

lib/chankins/web/controllers/version_controller.ex
defmodule Chankins.Web.VersionController do
  use Chankins.Web, :controller

  alias Chankins.ChangeManagement

  def index(conn, _params) do
    versions = ChangeManagement.list_versions()
    render(conn, "index.html", versions: versions)
  end

  def new(conn, _params) do
    changeset = ChangeManagement.change_version(%Chankins.ChangeManagement.Version{})
    releases = ChangeManagement.list_releases()
    render(conn, "new.html", changeset: changeset,  releases: releases)
  end

  def create(conn, %{"version" => version_params}) do
    case ChangeManagement.create_version(version_params) do
      {:ok, version} ->
        conn
        |> put_flash(:info, "Version created successfully.")
        |> redirect(to: version_path(conn, :show, version))
      {:error, %Ecto.Changeset{} = changeset} ->
        releases = ChangeManagement.list_releases()
        render(conn, "new.html", changeset: changeset,  releases: releases)
    end
  end

  def show(conn, %{"id" => id}) do
    version = ChangeManagement.get_version!(id)
    render(conn, "show.html", version: version)
  end

  def edit(conn, %{"id" => id}) do
    version = ChangeManagement.get_version!(id)
    changeset = ChangeManagement.change_version(version)
    releases = ChangeManagement.list_releases()
    render(conn, "edit.html", version: version, changeset: changeset, releases: releases)
  end

  def update(conn, %{"id" => id, "version" => version_params}) do
    version = ChangeManagement.get_version!(id)

    case ChangeManagement.update_version(version, version_params) do
      {:ok, version} ->
        conn
        |> put_flash(:info, "Version updated successfully.")
        |> redirect(to: version_path(conn, :show, version))
      {:error, %Ecto.Changeset{} = changeset} ->
        releases = ChangeManagement.list_releases()
        render(conn, "edit.html", version: version, changeset: changeset, releases: releases)
    end
  end

  def delete(conn, %{"id" => id}) do
    version = ChangeManagement.get_version!(id)
    {:ok, _version} = ChangeManagement.delete_version(version)

    conn
    |> put_flash(:info, "Version deleted successfully.")
    |> redirect(to: version_path(conn, :index))
  end
end

lib/chankins/web/views/version_view.ex
defmodule Chankins.Web.VersionView do
  use Chankins.Web, :view

  def map_releases_for_select(releases) do
    releases |> Enum.map(&map_release_for_select/1)
  end

  defp map_release_for_select(r) do
    {"#{r.name} (#{r.project.name})", r.id}
  end
end

lib/chankins/web/templates/version/edit.html.eex
<h2>Edit Version</h2>

<%= render "form.html", changeset: @changeset, releases: @releases,
                        action: version_path(@conn, :update, @version) %>

<span><%= link "Back", to: version_path(@conn, :show, @version) %></span>

lib/chankins/web/templates/version/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :version, class: "control-label" %>
    <%= text_input f, :version, class: "form-control" %>
    <%= error_tag f, :version %>
  </div>

  <div class="form-group">
    <%= label f, :release_date, class: "control-label" %>
    <%= datetime_select f, :release_date, class: "form-control" %>
    <%= error_tag f, :release_date %>
  </div>

  <div class="form-group">
    <%= label f, :release_id, class: "control-label" %>
    <%= select f, :release_id, map_releases_for_select(@releases), class: "form-control" %>
    <%= error_tag f, :release_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/chankins/web/templates/version/index.html.eex
<h2>Listing Versions</h2>

<table class="table">
  <thead>
    <tr>
      <th>Version</th>
      <th>Release date</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for version <- @versions do %>
    <tr>
      <td><%= version.version %></td>
      <td><%= version.release_date %></td>

      <td class="text-right">
        <span><%= link "Show", to: version_path(@conn, :show, version), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: version_path(@conn, :edit, version), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: version_path(@conn, :delete, version), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Version", to: version_path(@conn, :new) %></span>

lib/chankins/web/templates/version/new.html.eex
<h2>New Version</h2>

<%= render "form.html", changeset: @changeset, releases: @releases,
                        action: version_path(@conn, :create) %>

<span><%= link "Versions", to: version_path(@conn, :index) %></span>

lib/chankins/web/templates/version/show.html.eex
<h2><%= link @version.release.name, to: release_path(@conn, :show, @version.release) %></h2>

<h3><%= @version.version %></h3>

<div>
    <strong>Release date:</strong>
    <%= @version.release_date %>
</div>

<h4>Parameters:</h4>
<table class="table">
  <thead>
  <tr>
    <th>Key</th>
    <th>Value</th>
    <th>Group</th>

    <th></th>
  </tr>
  </thead>
  <tbody>
  <%= for parameter <- @version.parameters do %>
      <tr>
        <td><%= parameter.key %></td>
        <td><%= parameter.value %></td>
        <td><%= parameter.group %></td>

        <td class="text-right">
          <span><%= link "Show", to: parameter_path(@conn, :show, parameter), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Edit", to: parameter_path(@conn, :edit, parameter), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Delete", to: parameter_path(@conn, :delete, parameter), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<span><%= link "new Parameter", to: parameter_path(@conn, :new, version: @version.id) %></span>

<h4>Features:</h4>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for feature <- @version.features do %>
    <tr>
      <td><%= feature.title %></td>
      <td><%= feature.description %></td>

      <td class="text-right">
        <span><%= link "Show", to: feature_path(@conn, :show, feature), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: feature_path(@conn, :edit, feature), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: feature_path(@conn, :delete, feature), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<span><%= link "new Feature", to: feature_path(@conn, :new, version: @version.id) %></span>

<div>
  <span><%= link "Edit", to: version_path(@conn, :edit, @version) %></span>
  <span><%= link "Versions", to: version_path(@conn, :index) %></span>
  <span><%= link "Change Notes", to: change_notes_path(@conn, :show, version: @version.id), class: "btn btn-success" %></span>
</div>