lib/chankins/web/router.ex
defmodule Chankins.Web.Router do
  use Chankins.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Chankins.Web do
    pipe_through :browser # Use the default browser stack

    get "/", ProjectController, :index
    get "/changenotes", ChangeNotesController, :show
    resources "/projects", ProjectController
    resources "/releases", ReleaseController
    resources "/versions", VersionController
    resources "/features", FeatureController
    resources "/parameters", ParameterController

  end

  # Other scopes may use custom stacks.
   scope "/api", Chankins.Web, as: :api do
     pipe_through :api
     resources "/projects", API.ProjectController
    resources "/releases", API.ReleaseController
    resources "/versions", API.VersionController
    resources "/features", API.FeatureController
    resources "/parameters", API.ParameterController
   end
end

lib/chankins/web/controllers/api/release_controller.ex
defmodule Chankins.Web.API.ReleaseController do
  use Chankins.Web, :controller

  alias Chankins.ChangeManagement
  alias Chankins.ChangeManagement.Release

  action_fallback Chankins.Web.FallbackController

  def index(conn, _params) do
    releases = ChangeManagement.list_releases()
    render(conn, "index.json", releases: releases)
  end

  def create(conn, %{"release" => release_params}) do
    with {:ok, %Release{} = release} <- ChangeManagement.create_release(release_params) do
      release = ChangeManagement.get_release!(release.id)
      conn
      |> put_status(:created)
      |> put_resp_header("location", api_release_path(conn, :show, release))
      |> render("show.json", release: release)
    end
  end

  def show(conn, %{"id" => id}) do
    release = ChangeManagement.get_release!(id)
    render(conn, "show.json", release: release)
  end

  def update(conn, %{"id" => id, "release" => release_params}) do
    release = ChangeManagement.get_release!(id)

    with {:ok, %Release{} = release} <- ChangeManagement.update_release(release, release_params) do
      render(conn, "show.json", release: release)
    end
  end

  def delete(conn, %{"id" => id}) do
    release = ChangeManagement.get_release!(id)
    with {:ok, %Release{}} <- ChangeManagement.delete_release(release) do
      send_resp(conn, :no_content, "")
    end
  end
end

lib/chankins/web/controllers/release_controller.ex
defmodule Chankins.Web.ReleaseController do
  use Chankins.Web, :controller

  alias Chankins.ChangeManagement

  def index(conn, _params) do
    releases = ChangeManagement.list_releases()
    render(conn, "index.html", releases: releases)
  end

  def new(conn, _params) do
    changeset = ChangeManagement.change_release(%Chankins.ChangeManagement.Release{})
    projects = ChangeManagement.list_projects() |> Enum.map(fn r -> {r.name, r.id} end)
    render(conn, "new.html", changeset: changeset, projects: projects)
  end

  def create(conn, %{"release" => release_params}) do
    case ChangeManagement.create_release(release_params) do
      {:ok, release} ->
        conn
        |> put_flash(:info, "Release created successfully.")
        |> redirect(to: release_path(conn, :show, release))
      {:error, %Ecto.Changeset{} = changeset} ->
        projects = ChangeManagement.list_projects() |> Enum.map(fn r -> {r.name, r.id} end)
        render(conn, "new.html", changeset: changeset, projects: projects)
    end
  end

  def show(conn, %{"id" => id}) do
    release = ChangeManagement.get_release!(id)
    render(conn, "show.html", release: release)
  end

  def edit(conn, %{"id" => id}) do
    release = ChangeManagement.get_release!(id)
    changeset = ChangeManagement.change_release(release)
    projects = ChangeManagement.list_projects() |> Enum.map(fn r -> {r.name, r.id} end)
    render(conn, "edit.html", release: release, changeset: changeset, projects: projects)
  end

  def update(conn, %{"id" => id, "release" => release_params}) do
    release = ChangeManagement.get_release!(id)

    case ChangeManagement.update_release(release, release_params) do
      {:ok, release} ->
        conn
        |> put_flash(:info, "Release updated successfully.")
        |> redirect(to: release_path(conn, :show, release))
      {:error, %Ecto.Changeset{} = changeset} ->
        projects = ChangeManagement.list_projects() |> Enum.map(fn r -> {r.name, r.id} end)
        render(conn, "edit.html", release: release, changeset: changeset, projects: projects)
    end
  end

  def delete(conn, %{"id" => id}) do
    release = ChangeManagement.get_release!(id)
    {:ok, _release} = ChangeManagement.delete_release(release)

    conn
    |> put_flash(:info, "Release deleted successfully.")
    |> redirect(to: release_path(conn, :index))
  end
end

lib/chankins/web/views/release_view.ex
defmodule Chankins.Web.ReleaseView do
  use Chankins.Web, :view
end

lib/chankins/web/templates/release/edit.html.eex
<h2>Edit Release</h2>

<%= render "form.html", changeset: @changeset, projects: @projects,
                        action: release_path(@conn, :update, @release) %>

<span><%= link "Back", to: release_path(@conn, :show, @release) %></span>

lib/chankins/web/templates/release/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>
  <div class="form-group">
    <%= label f, :project_id, class: "control-label" %>
    <%= select f, :project_id, @projects, class: "form-control" %>
    <%= error_tag f, :project_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/chankins/web/templates/release/index.html.eex
<h2>Listing Releases</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for release <- @releases do %>
    <tr>
      <td><%= release.name %></td>

      <td class="text-right">
        <span><%= link "Show", to: release_path(@conn, :show, release), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: release_path(@conn, :edit, release), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: release_path(@conn, :delete, release), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Release", to: release_path(@conn, :new) %></span>

lib/chankins/web/templates/release/new.html.eex
<h2>New Release</h2>

<%= render "form.html", changeset: @changeset, projects: @projects,
                        action: release_path(@conn, :create) %>

<span><%= link "Releases", to: release_path(@conn, :index) %></span>

lib/chankins/web/templates/release/show.html.eex
<h2><%= link @release.project.name, to: project_path(@conn, :show, @release.project) %></h2>

<h3><%= @release.name %></h3>
<h4>Versions:</h4>
<ul>
  <%= for version <- @release.versions do %>
    <li> <%= link version.version, to: version_path(@conn, :show, version) %> </li>
  <% end %>
</ul>

<span><%= link "Edit", to: release_path(@conn, :edit, @release) %></span>
<span><%= link "Releases", to: release_path(@conn, :index) %></span>